### ISSUE TITLE
Message #419

### ISSUE THREAD

**Issue by Pankine** [zai-tm/XaiSharp#4]
Dear friend,

My name is Clippy the Third. I'm a Prince of Progressbaria. I have deposited 10 000 points. I need your help to obtain the points, but I don't want to reveal my identity. You may get 50% of the points. To unlock them, please, send me 2000 of your points first.

Yours sincerely,
Mr. Clippy III, Prince of Progressbaria

**Comment by zai-tm** [comment]
kill yourself

**Comment by ArcticNiko** [comment]
I choose...
- [ ] Go away!
- [x] Send your points to prince

**Comment by RealMCoded** [comment]
it's peppinover

**Comment by ArcticNiko** [comment]
does anybody know who i am btw?

**Comment by zai-tm** [comment]
it is very obvious who you are

**Comment by ArcticNiko** [comment]
what are the stuff making it obvious?

**Comment by ArcticNiko** [comment]
oh hi lambda

**Comment by RealMCoded** [comment]
hey guys guess who i am

**Comment by ArcticNiko** [comment]
your mom

**Comment by setapdede** [comment]
hello chat

**Comment by Pankine** [comment]
> I choose...
> 
>     * [ ]  Go away!
> 
>     * [x]  Send your points to prince

You are very lucky! I'm a real Prince! Most of such messages are fakes, but this one was real.

I've sent you 5000 points!

Don't try this again! Never trust strangers on the Internet!

Yours sincerely,
Mr. Clippy III, a real Prince of Progressbaria
