### ISSUE TITLE
Where is the bot hosted?=

### ISSUE THREAD

**Issue by jdopss** [zai-tm/XaiSharp#7]
Where???

**Comment by dewsmith0** [comment]
We host it on the Linode server at pb95discord.com, which 5jiji pays for

**Comment by zai-tm** [comment]
why did you make an issue for this

**Comment by RealMCoded** [comment]
![baby](https://github.com/zai-tm/XaiSharp/assets/34777184/56aa0da0-24a8-4212-9ef1-3236e3baca7c)

**Comment by jdopss** [comment]
you dont really respond on discord when  i ping tbf

**Comment by dewsmith0** [comment]
Because he's busy?

**Comment by RealMCoded** [comment]
> you dont really respond on discord when i ping tbf

What's your discord handle?

**Comment by dewsmith0** [comment]
That's KerbMario's alt I think

**Comment by jdopss** [comment]
yea I'm kerb

**Comment by ArcticNiko** [comment]
dead chat

**Comment by zai-tm** [comment]
shut the fuck up

**Comment by zai-tm** [comment]
shut the fuck up

**Comment by RealMCoded** [comment]
why can't i baby react on github
